/*************** 함수 ***************/

-- 1. 문자함수

SELECT FIRST_NAME, UPPER(FIRST_NAME), EMAIL, LOWER(EMAIL)
    FROM EMPLOYEES;
    
SELECT FIRST_NAME, LENGTH(FIRST_NAME)
    FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) >= 8;

SELECT JOB_ID
    ,SUBSTR(JOB_ID,1,2)
    ,SUBSTR(JOB_ID,4)
 FROM EMPLOYEES;
    
SELECT HIRE_DATE
    ,REPLACE(HIRE_DATE, '/', '-')
    ,REPLACE(HIRE_DATE, '/')
 FROM EMPLOYEES;
 
 SELECT CONCAT('입사일은 ', HIRE_DATE) AS 자기소개
  FROM EMPLOYEES;

SELECT '입사일은 ' || HIRE_DATE || '입니다.' AS 자기소개
 FROM EMPLOYEES;
 
 -- 2. 숫자함수
SELECT MOD(10,2)
    ,MOD(9,2)
    ,ROUND(15.65)
    ,ROUND(15.65,1)
    ,TRUNC(15.65)
    ,TRUNC(15.65,1)
 FROM DUAL;
 
 -- 3. 날짜함수
SELECT SYSDATE
    ,SYSDATE+1 AS 하루더함
    ,SYSDATE+1/24 AS 한시간더함
    ,SYSDATE+1/24/60 AS 일분더함
    ,SYSDATE+1/24/60/60 AS 일초더함
 FROM DUAL;
 
SELECT SYSDATE
    ,ADD_MONTHS(SYSDATE,1) AS 한달뒤
    ,ADD_MONTHS(SYSDATE,-1) AS 한달전
 FROM DUAL;
 
