SELECT EMPLOYEE_ID, EMAIL, SALARY
  FROM EMPLOYEES
 ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, EMAIL, SALARY
  FROM(
       SELECT EMPLOYEE_ID, EMAIL, SALARY
         FROM EMPLOYEES
        ORDER BY SALARY DESC
       )
  WHERE ROWNUM <= 5;
  
SELECT E.EMPLOYEE_ID, E.EMAIL, E.SALARY, D.DEPARTMENT_NAME, D.LOCATION_ID
  FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
   ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
 WHERE E.SALARY >= 14000;
 
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, A.MANAGER_ID, B.FIRST_NAME, B.LAST_NAME
  FROM DEPARTMENTS A LEFT OUTER JOIN EMPLOYEES B
 ON(A.MANAGER_ID = B.EMPLOYEE_ID)
    WHERE A.LOCATION_ID = 1700;
    

CREATE TABLE TB_STUDENT(
    STUDENT_ID NUMBER NOT NULL,
    STUDENT_NAME VARCHAR2(50) NOT NULL,
    AGE NUMBER DEFAULT 20,
    MAJOR_ID VARCHAR2(50)
    );

CREATE TABLE TB_MAJOR(
    MAJOR_ID VARCHAR2(50) NOT NULL,
    MAJOR_NAME VARCHAR2(100) NOT NULL,
    INST_DY VARCHAR2(8) NOT NULL
    );

ALTER TABLE TB_STUDENT ADD CONSTRAINT PK_STUDNET PRIMARY KEY(STUDENT_ID);

ALTER TABLE TB_MAJOR ADD CONSTRAINT PK_MAJOR PRIMARY KEY(MAJOR_ID);

INSERT INTO TB_MAJOR
    VALUES('M0001', '정보공학과', '19960201');

INSERT INTO TB_MAJOR
    VALUES('M0002', '경영학과', '20000302');
    
SELECT *
  FROM TB_STUDENT;
  
SELECT *
  FROM TB_MAJOR;
  
INSERT INTO TB_STUDENT
    VALUES(1000, '김철수', 20, 'M0001');
    
INSERT INTO TB_STUDENT
    VALUES(2000, '홍길동', 21, 'M0002');
    
UPDATE TB_MAJOR
  SET MAJOR_NAME = '인공지능융합과'
 WHERE MAJOR_NAME = '정보공학과';
 
DELETE FROM TB_STUDENT
  WHERE STUDENT_ID = 1000;

COMMIT;